# Generated by Django 3.2.20 on 2023-11-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelresult',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelresult',
            name='user_metadata',
            field=models.JSONField(default=dict),
        ),
    ]
