# Generated by Django 3.2.20 on 2024-10-30 22:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benchmark', '0002_alter_benchmark_demo_dataset_tarball_url'),
        ('dataset', '0004_auto_20231211_1827'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mlcube', '0002_alter_mlcube_unique_together'),
        ('execution', '0002_auto_20231124_0208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelResult',
            new_name='Execution',
        ),
    ]
