# Generated by Django 3.2.20 on 2024-11-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_rename_modelresult_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='evaluation_report',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='execution',
            name='model_report',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
