# Generated by Django 4.2.11 on 2025-06-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0004_execution_evaluation_report_execution_finalized_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="execution",
            name="finalized",
            field=models.BooleanField(default=False),
        ),
    ]
