# Generated by Django 4.2.23 on 2025-08-01 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ca', '0002_createmedperfca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mlcube', '0002_alter_mlcube_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('associated_ca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ca.ca')),
                ('model_mlcube', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_mlcube', to='mlcube.mlcube')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='containerca',
            constraint=models.UniqueConstraint(fields=('associated_ca', 'model_mlcube'), name='Unique_CA_and_Model'),
        ),
    ]
