container_type: DockerImage
image: mlcommons/chestxray-tutorial-prep:0.0.1
tasks:
  prepare:
    run_args:
      command: python3 /project/prepare.py
    input_volumes:
      data_path:
        mount_path: /mlcommons/volumes/raw_data
        type: directory
      labels_path:
        mount_path: /mlcommons/volumes/raw_labels
        type: directory
      parameters_file:
        mount_path: /mlcommons/volumes/parameters/parameters_file.yaml
        type: file
    output_volumes:
      output_path:
        mount_path: /mlcommons/volumes/data
        type: directory
      output_labels_path:
        mount_path: /mlcommons/volumes/labels
        type: directory
  sanity_check:
    run_args:
      command: python3 /project/sanity_check.py
    input_volumes:
      data_path:
        mount_path: /mlcommons/volumes/data
        type: directory
      labels_path:
        mount_path: /mlcommons/volumes/labels
        type: directory
      parameters_file:
        mount_path: /mlcommons/volumes/parameters/parameters_file.yaml
        type: file
  statistics:
    run_args:
      command: python3 /project/statistics.py
    input_volumes:
      data_path:
        mount_path: /mlcommons/volumes/data
        type: directory
      labels_path:
        mount_path: /mlcommons/volumes/labels
        type: directory
      parameters_file:
        mount_path: /mlcommons/volumes/parameters/parameters_file.yaml
        type: file
    output_volumes:
      output_path:
        mount_path: /mlcommons/volumes/statistics/statistics.yaml
        type: file
