{
  "image": "mlcommons/rano-data-prep-mlcube:1.0.11",
  "tasks":
    {
      "prepare":
        {
          "run_args":
            {
              "command":
                [
                  "prepare",
                  "--data_path=/mlcube_io0/",
                  "--labels_path=/mlcube_io1/",
                  "--parameters_file=/mlcube_io2/parameters.yaml",
                  "--models=/mlcube_io3/models",
                  "--output_path=/mlcube_io4/",
                  "--output_labels_path=/mlcube_io5/",
                  "--report_file=/mlcube_io6/report.yaml",
                  "--metadata_path=/mlcube_io7/",
                ],
            },
          "input_volumes":
            {
              "data_path": { "type": "directory", "mount_path": "/mlcube_io0" },
              "labels_path":
                { "type": "directory", "mount_path": "/mlcube_io1" },
              "parameters_file":
                { "type": "file", "mount_path": "/mlcube_io2/parameters.yaml" },
              "additional_files":
                { "type": "directory", "mount_path": "/mlcube_io3" },
            },
          "output_volumes":
            {
              "output_path":
                { "type": "directory", "mount_path": "/mlcube_io4" },
              "report_file":
                { "type": "file", "mount_path": "/mlcube_io6/report.yaml" },
              "metadata_path":
                { "type": "directory", "mount_path": "/mlcube_io7" },
              "output_labels_path":
                { "type": "directory", "mount_path": "/mlcube_io5" },
            },
        },
      "statistics":
        {
          "run_args":
            {
              "command":
                [
                  "statistics",
                  "--data_path=/mlcube_io0/",
                  "--labels_path=/mlcube_io1/",
                  "--parameters_file=/mlcube_io2/parameters.yaml",
                  "--metadata_path=/mlcube_io3/",
                  "--output_path=/mlcube_io4/statistics.yaml",
                ],
            },
          "input_volumes":
            {
              "data_path": { "type": "directory", "mount_path": "/mlcube_io0" },
              "labels_path":
                { "type": "directory", "mount_path": "/mlcube_io1" },
              "metadata_path":
                { "type": "directory", "mount_path": "/mlcube_io3" },
              "parameters_file":
                { "type": "file", "mount_path": "/mlcube_io2/parameters.yaml" },
            },
          "output_volumes":
            {
              "output_path":
                { "type": "file", "mount_path": "/mlcube_io4/statistics.yaml" },
            },
        },
      "sanity_check":
        {
          "run_args":
            {
              "command":
                [
                  "sanity_check",
                  "--data_path=/mlcube_io0/",
                  "--labels_path=/mlcube_io1/",
                  "--parameters_file=/mlcube_io2/parameters.yaml",
                  "--metadata_path=/mlcube_io3/",
                ],
            },
          "input_volumes":
            {
              "data_path": { "type": "directory", "mount_path": "/mlcube_io0" },
              "labels_path":
                { "type": "directory", "mount_path": "/mlcube_io1" },
              "metadata_path":
                { "type": "directory", "mount_path": "/mlcube_io3" },
              "parameters_file":
                { "type": "file", "mount_path": "/mlcube_io2/parameters.yaml" },
            },
          "output_volumes": {},
        },
    },
  "container_type": "DockerImage",
}
