# Generated by Django 4.2.23 on 2025-11-03 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mlcube', '0002_alter_mlcube_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlCubeKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('encrypted_key_base64', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificate.certificate')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlcube.mlcube')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='mlcubekey',
            constraint=models.UniqueConstraint(condition=models.Q(('is_valid', True)), fields=('certificate', 'container'), name='One_Key_Per_Certificate_And_Container'),
        ),
    ]
