[ req ]
prompt = no
default_md = sha384
distinguished_name = req_distinguished_name

[ req_distinguished_name ]
commonName = testfladmin@example.com

[ alt_names ]
DNS.1 = testfladmin@example.com

[ v3_client ]
basicConstraints = critical,CA:FALSE
keyUsage = critical,digitalSignature,keyAgreement
subjectAltName = @alt_names
extendedKeyUsage = critical,clientAuth

[ v3_server ]
basicConstraints = critical,CA:FALSE
keyUsage = critical,digitalSignature,keyAgreement
subjectAltName = @alt_names
extendedKeyUsage = critical,serverAuth

[ v3_client_crt ]
basicConstraints = critical,CA:FALSE
subjectAltName = @alt_names

[ v3_server_crt ]
basicConstraints = critical,CA:FALSE
subjectAltName = @alt_names