# Generated by Django 4.2.23 on 2025-08-11 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('certificate', '0001_initial'), ('certificate', '0002_remove_certificate_unique_certificate_per_ca_and_owner_and_more')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ca', '0002_createmedperfca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('certificate_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ca_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ca.ca')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(fields=('certificate_content', 'ca_id', 'owner'), name='Unique_Certificate_Per_CA_and_Owner'),
        ),
        migrations.RemoveConstraint(
            model_name='certificate',
            name='Unique_Certificate_Per_CA_and_Owner',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate_content',
            new_name='certificate_content_base64',
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(fields=('certificate_content_base64', 'ca_id', 'owner'), name='Unique_Certificate_Per_CA_and_Owner'),
        ),
    ]
