# Generated by Django 4.2.23 on 2026-03-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='certificate',
            name='One_Certificate_Per_User_And_CA',
        ),
        migrations.AddField(
            model_name='certificate',
            name='key_type',
            field=models.CharField(choices=[('RSA', 'RSA'), ('EC', 'EC')], default='RSA', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_valid', True)), fields=('owner', 'ca', 'key_type'), name='One_Certificate_type_Per_User_And_CA'),
        ),
    ]
