# Generated by Django 4.2.23 on 2025-08-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='certificate',
            name='Unique_Certificate_Per_CA_and_Owner',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate_content',
            new_name='certificate_content_base64',
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(fields=('certificate_content_base64', 'ca_id', 'owner'), name='Unique_Certificate_Per_CA_and_Owner'),
        ),
    ]
