container_type: DockerImage
image: mlcommons/chestxray-tutorial-cnn:0.0.1
tasks:
  infer:
    input_volumes:
      data_path:
        mount_path: /mlcommons/volumes/data
        type: directory
      parameters_file:
        mount_path: /mlcommons/volumes/parameters/parameters_file.yaml
        type: file
      additional_files:
        mount_path: /mlcommons/volumes/additional_files
        type: directory
    output_volumes:
      output_path:
        mount_path: /mlcommons/volumes/predictions
        type: directory
