# Generated by Django 4.2.23 on 2026-02-15 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mlcube', '0005_alter_mlcube_unique_together_alter_mlcube_image_hash_and_more'),
        ('asset', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('state', models.CharField(choices=[('DEVELOPMENT', 'DEVELOPMENT'), ('OPERATION', 'OPERATION')], default='DEVELOPMENT', max_length=100)),
                ('is_valid', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('user_metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('type', models.CharField(choices=[('ASSET', 'ASSET'), ('CONTAINER', 'CONTAINER')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asset.asset')),
                ('container', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mlcube.mlcube')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['modified_at'],
            },
        ),
    ]
