# Generated by Django 4.2.23 on 2026-03-15 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator_association', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExperimentAggregator',
        ),
    ]
