# Generated by Django 4.2.23 on 2026-03-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchmarkdataset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarkdataset',
            name='signature',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
