# Generated by Django 3.2.16 on 2022-11-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchmarkdataset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarkdataset',
            name='metadata',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
