# Generated by Django 4.2.23 on 2026-02-15 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
        ('benchmarkmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarkmodel',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='model.model'),
        ),
    ]
