# Generated by Django 4.2.23 on 2026-02-15 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_createmodelsfromcontainers'),
        ('benchmarkmodel', '0002_benchmarkmodel_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benchmarkmodel',
            name='model_mlcube',
        ),
        migrations.AlterField(
            model_name='benchmarkmodel',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.model'),
        ),
    ]
