# Generated by Django 3.2.16 on 2022-11-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchmarkmodel', '0002_rename_results_benchmarkmodel_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benchmarkmodel',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='benchmarkmodel',
            name='priority',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
