# Generated by Django 4.2.23 on 2026-03-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchmarkmodel', '0003_remove_benchmarkmodel_model_mlcube_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarkmodel',
            name='signature',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
