FROM local/openfl:local

ENV GANDLF_VERSION 60c9d28aa5e1b951e75ed5646ac20d5790fe4317
ENV FL_WORKSPACE /mlcube_project/fl_workspace
ENV LANG C.UTF-8
ENV CUDA_VISIBLE_DEVICES="0"
# TODO: combine docker images (cpu and gpu)
# TODO: make necessary changes since now user is not root

# install software requirements needed by GaNDLF
RUN apt-get update && apt-get upgrade -y && apt-get install -y git zlib1g-dev libffi-dev libgl1 libgtk2.0-dev gcc g++

# install GaNDLF (cpu)
RUN pip install torch==1.13.1+cu116 torchvision==0.14.1+cu116 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu116 && \
    pip install openvino-dev==2023.0.1 && \
    git clone https://github.com/mlcommons/GaNDLF.git && \
    cd GaNDLF && git checkout $GANDLF_VERSION && \
    pip install -e .


# install workspace requirements
COPY ./fl_workspace/requirements.txt $FL_WORKSPACE/requirements.txt
RUN pip install --no-cache-dir -r $FL_WORKSPACE/requirements.txt

# Copy mlcube workspace
COPY . /mlcube_project

ENTRYPOINT ["python", "/mlcube_project/mlcube.py"]