steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: 
      [
      "build", 
      "-t", 
      "${_REGION}-${_ARTIFACT_REGISTRY_DOMAIN}/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}",
      "-f",
      "Dockerfile.cloudbuild", 
      "."
      ]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: 
      [
        "push", 
        "${_REGION}-${_ARTIFACT_REGISTRY_DOMAIN}/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}"
      ]

  - id: "apply migrations"
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "${_REGION}-${_ARTIFACT_REGISTRY_DOMAIN}/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}",
        "-s",
        "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "-e",
        "SETTINGS_SECRETS_NAME=${_SECRET_SETTINGS_NAME}",
        "--",
        "python",
        "manage.py",
        "migrate",
      ]

  - id: "collect static"
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "${_REGION}-${_ARTIFACT_REGISTRY_DOMAIN}/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}",
        "-s",
        "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "-e",
        "SETTINGS_SECRETS_NAME=${_SECRET_SETTINGS_NAME}",
        "--",
        "python",
        "manage.py",
        "collectstatic",
        "--verbosity",
        "2",
        "--no-input",
      ]

  - id: "cloud run deploy"
    name: "gcr.io/cloud-builders/gcloud"
    args: 
      [
        "run", 
        "deploy", 
        "${_SERVICE_NAME}", 
        "--platform", 
        "managed", 
        "--region", 
        "${_REGION}", 
        "--image", 
        "${_REGION}-${_ARTIFACT_REGISTRY_DOMAIN}/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:latest", 
        "--add-cloudsql-instances", 
        "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}", 
        "--allow-unauthenticated"
      ]

substitutions:
  _REGION: us-west1
  _ARTIFACT_REGISTRY_DOMAIN: docker.pkg.dev
  _REPO_NAME: medperf-repo
  _IMAGE_NAME: medperf-api-dev
  _SERVICE_NAME: medperf-api-dev-service
  _SECRET_SETTINGS_NAME: django-dev-settings
  _INSTANCE_NAME: medperf-dev
