container_type: DockerImage
image: {{ cookiecutter.docker_image_name }}
tasks:
  evaluate:
    input_volumes:
      predictions:
        mount_path: /mlcommons/volumes/predictions
        type: directory
      labels:
        mount_path: /mlcommons/volumes/labels
        type: directory
      parameters_file:
        mount_path: /mlcommons/volumes/parameters/parameters_file.yaml
        type: file
    output_volumes:
      output_path:
        mount_path: /mlcommons/volumes/results/results.yaml
        type: file
