# Generated by Django 4.2.23 on 2025-08-11 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('mlcube_ca_encrypted_key', '0001_initial'), ('mlcube_ca_encrypted_key', '0002_alter_modelcaencryptedkey_data_owner_and_more'), ('mlcube_ca_encrypted_key', '0003_rename_encrypted_key_modelcaencryptedkey_encrypted_key_base64'), ('mlcube_ca_encrypted_key', '0004_modelcaencryptedkey_name')]

    dependencies = [
        ('mlcube_ca_association', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCAEncryptedKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_key', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ca_association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlcube_ca_association.containerca')),
                ('data_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_owner', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='modelcaencryptedkey',
            constraint=models.UniqueConstraint(fields=('ca_association', 'data_owner'), name='One_Key_Per_Owner_And_Association'),
        ),
        migrations.AlterField(
            model_name='modelcaencryptedkey',
            name='data_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modelcaencryptedkey',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='modelcaencryptedkey',
            old_name='encrypted_key',
            new_name='encrypted_key_base64',
        ),
        migrations.AddField(
            model_name='modelcaencryptedkey',
            name='name',
            field=models.CharField(default='EMPTYNAME', max_length=20),
            preserve_default=False,
        ),
    ]
