# Generated by Django 4.2.23 on 2025-08-07 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mlcube_ca_encrypted_key', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcaencryptedkey',
            name='data_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modelcaencryptedkey',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
