# Generated by Django 4.2.23 on 2025-08-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlcube_ca_encrypted_key', '0002_alter_modelcaencryptedkey_data_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelcaencryptedkey',
            old_name='encrypted_key',
            new_name='encrypted_key_base64',
        ),
    ]
