# Generated by Django 4.2.23 on 2025-08-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcube_ca_encrypted_key', '0003_rename_encrypted_key_modelcaencryptedkey_encrypted_key_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcaencryptedkey',
            name='name',
            field=models.CharField(default='EMPTYNAME', max_length=20),
            preserve_default=False,
        ),
    ]
