# Generated by Django 4.2.23 on 2025-11-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca_association', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExperimentCA',
        ),
    ]
