# Generated by Django 4.2.11 on 2024-04-29 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mlcube", "0002_alter_mlcube_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingExperiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("description", models.CharField(blank=True, max_length=100)),
                ("docs_url", models.CharField(blank=True, max_length=100)),
                ("demo_dataset_tarball_url", models.CharField(max_length=256)),
                ("demo_dataset_tarball_hash", models.CharField(max_length=100)),
                ("demo_dataset_generated_uid", models.CharField(max_length=128)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DEVELOPMENT", "DEVELOPMENT"),
                            ("OPERATION", "OPERATION"),
                        ],
                        default="DEVELOPMENT",
                        max_length=100,
                    ),
                ),
                ("is_valid", models.BooleanField(default=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                        ],
                        default="PENDING",
                        max_length=100,
                    ),
                ),
                ("plan", models.JSONField(blank=True, null=True)),
                (
                    "user_metadata",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "data_preparation_mlcube",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_exp",
                        to="mlcube.mlcube",
                    ),
                ),
                (
                    "fl_mlcube",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fl_mlcube",
                        to="mlcube.mlcube",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["modified_at"],
            },
        ),
    ]
