# Generated by Django 4.2.11 on 2024-07-28 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mlcube", "0002_alter_mlcube_unique_together"),
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingexperiment",
            name="fl_admin_mlcube",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fl_admin_mlcube",
                to="mlcube.mlcube",
            ),
        ),
    ]
