# Generated by Django 4.2.11 on 2025-09-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_trainingexperiment_fl_admin_mlcube"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingexperiment",
            name="description",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="trainingexperiment",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
