# Generated by Django 4.2.23 on 2025-09-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
        ('training', '0002_trainingexperiment_fl_admin_mlcube'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetTrainingKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('kit', models.TextField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.trainingexperiment')),
            ],
        ),
        migrations.CreateModel(
            name='AggregatorTrainingKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit', models.TextField()),
                ('aggregator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aggregator.aggregator')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.trainingexperiment')),
            ],
        ),
    ]
