# Generated by Django 4.2.26 on 2026-02-24 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_alter_aggregator_name'),
        ('training', '0003_alter_trainingexperiment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingexperiment',
            name='aggregator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_experiments', to='aggregator.aggregator'),
        ),
    ]
