apiVersion: v1
kind: Pod
metadata:
  name: {pod_name}
  annotations:
    io.katacontainers.config.runtime.cc_init_data: "{initdata}"
    io.containerd.cri.runtime-handler: kata-remote
spec:
  runtimeClassName: kata-remote
  containers:
    - name: {model_container_name}
      image: {model_container_image}
      env:
      - name: DATASET_KBS_CERT
        value: "{kbs_cert}"
      - name: DATASET_KBS_URL
        value: "https://{kbs_address}:{kbs_port}"
      - name: DATASET_SECRET_ID
        value: "{secret_id}"
      securityContext:
        privileged: false
        seccompProfile:
          type: RuntimeDefault

    - name: {metrics_container_name}
      image: {metrics_container_image}
      securityContext:
        privileged: false
        seccompProfile:
          type: RuntimeDefault
EOF
