# Generated by Django 4.2.11 on 2024-04-23 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finished", models.BooleanField(default=False)),
                ("participants", models.JSONField()),
                ("report", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "training_exp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="training.trainingexperiment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
