# Generated by Django 4.2.11 on 2025-09-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainingevent", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingevent",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
