#The script is invoked manually with all settings provided in the secret
#It assumes that DB is created before the script run
#Inorder to deploy a service, pass sha-id of the already built image
#Command:  gcloud builds submit --config=cloudbuild.yaml --substitutions=SHORT_SHA=<sha-id>
steps:
  - id: "deploy cloud run"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_CLOUD_RUN_SERVICE_NAME}",
        "--platform",
        "managed",
        "--region",
        "${_REGION}",
        "--image",
        "${_REGION}-${_ARTIFACT_REGISTRY_DOMAIN}/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:${SHORT_SHA}",
        "--add-cloudsql-instances",
        "${PROJECT_ID}:${_REGION}:${_SQL_INSTANCE_NAME}",
        "--set-env-vars",
        "SETTINGS_SECRETS_NAME=${_SECRET_SETTINGS_NAME}",
        "--allow-unauthenticated",
        "--min-instances",
        "${_CLOUD_RUN_MIN_INSTANCES}",
        "--port",
        "${_PORT}",
        "--service-account",
        "${_SERVICE_ACCOUNT}"
      ]

substitutions:
  _REGION: us-west1
  _ARTIFACT_REGISTRY_DOMAIN: docker.pkg.dev
  _REPO_NAME: medperf-repo
  _IMAGE_NAME: medperf-ca
  _CLOUD_RUN_SERVICE_NAME: medperf-ca
  _CLOUD_RUN_MIN_INSTANCES: "1"
  _SECRET_SETTINGS_NAME: medperf-ca-settings
  _SQL_INSTANCE_NAME: medperf-dev
  _PORT: "443"
  _SERVICE_ACCOUNT: "medperf-ca@medperf-330914.iam.gserviceaccount.com"

options:
  dynamic_substitutions: true
