seed: 2784
train_percent: 0.8
medperf_report_stages:
- "IDENTIFIED"
- "VALIDATED"
- "MISSING_MODALITIES"
- "EXTRA_MODALITIES"
- "VALIDATION_FAILED"
- "CONVERTED_TO_NIfTI"
- "NIfTI_CONVERSION_FAILED"
- "BRAIN_EXTRACT_FINISHED"
- "BRAIN_EXTRACT_FINISHED"
- "TUMOR_EXTRACT_FAILED"
- "MANUAL_REVIEW_COMPLETE"
- "MANUAL_REVIEW_REQUIRED"
- "MULTIPLE_ANNOTATIONS_ERROR"
- "COMPARISON_COMPLETE"
- "EXACT_MATCH_IDENTIFIED"
- "ANNOTATION_COMPARISON_FAILED"
- "ANNOTATION_CONFIRMED"
- "DONE"