# Generated by Django 3.2.20 on 2024-10-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcube', '0002_alter_mlcube_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlcube',
            name='stages_hash',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mlcube',
            name='stages_url',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
