# Generated by Django 4.2.23 on 2025-09-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0002_createmedperfca'),
        ('mlcube', '0002_alter_mlcube_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlcube',
            name='trusted_cas',
            field=models.ManyToManyField(blank=True, to='ca.ca'),
        ),
    ]
