# Generated by Django 4.2.23 on 2025-11-04 14:05

from django.db import migrations, models


def convert_str_hash_to_json_hash(apps, schema_editor):
    MlCube = apps.get_model("mlcube", "MlCube")
    for mlcube in MlCube.objects.all():
        mlcube.mlcube_hash_temp = {"default": mlcube.mlcube_hash}
        mlcube.save()


def convert_json_hash_to_str_hash(apps, schema_editor):
    MlCube = apps.get_model("mlcube", "MlCube")
    for mlcube in MlCube.objects.all():
        mlcube.mlcube_hash = list(mlcube.mlcube_hash_temp.values())[0]
        mlcube.save()


class Migration(migrations.Migration):

    replaces = [
        ("mlcube", "0003_tmp_mlcube_hash"),
        (
            "mlcube",
            "0004_alter_mlcube_unique_together_mlcube_mlcube_hash_temp_and_more",
        ),
        ("mlcube", "0005_rename_mlcube_hash_temp_mlcube_mlcube_hash_and_more"),
    ]

    dependencies = [
        ("mlcube", "0002_alter_mlcube_unique_together"),
    ]

    operations = [
        migrations.RunPython(
            code=convert_str_hash_to_json_hash,
            reverse_code=convert_json_hash_to_str_hash,
        ),
        migrations.AlterUniqueTogether(
            name="mlcube",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="mlcube",
            name="mlcube_hash_temp",
            field=models.JSONField(default=dict),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="mlcube",
            unique_together={
                (
                    "image_tarball_hash",
                    "image_hash",
                    "additional_files_tarball_hash",
                    "mlcube_hash_temp",
                    "parameters_hash",
                )
            },
        ),
        migrations.RemoveField(
            model_name="mlcube",
            name="mlcube_hash",
        ),
        migrations.RenameField(
            model_name="mlcube",
            old_name="mlcube_hash_temp",
            new_name="mlcube_hash",
        ),
        migrations.AlterUniqueTogether(
            name="mlcube",
            unique_together={
                (
                    "image_tarball_hash",
                    "image_hash",
                    "additional_files_tarball_hash",
                    "mlcube_hash",
                    "parameters_hash",
                )
            },
        ),
    ]
