# Generated by Django 3.2.16 on 2022-11-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcube', '0003_auto_20221021_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlcube',
            name='git_parameters_url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='mlcube',
            name='parameters_hash',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
