# Generated by Django 3.2.16 on 2023-07-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcube', '0003_auto_20221109_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlcube',
            name='image_hash',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='mlcube',
            unique_together={('image_tarball_url', 'image_tarball_hash', 'image_hash', 'additional_files_tarball_url', 'additional_files_tarball_hash', 'git_mlcube_url', 'mlcube_hash', 'git_parameters_url', 'parameters_hash')},
        ),
    ]
