# Generated by Django 4.2.23 on 2025-11-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlcube', '0003_alter_mlcube_name'),
        ('mlcube', '0003_convert_image_hash_to_json'),
    ]

    operations = [
    ]
