# Generated by Django 4.2.23 on 2025-11-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlcube', '0003_alter_mlcube_name'),
        ('mlcube', '0003_alter_mlcube_unique_together_mlcube_container_config_and_more'),
    ]

    operations = [
    ]
