# Generated by Django 4.2.23 on 2025-12-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcube', '0004_alter_mlcube_unique_together_mlcube_container_config_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mlcube',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='mlcube',
            name='image_hash',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='mlcube',
            unique_together={('image_hash', 'additional_files_tarball_hash', 'container_config', 'parameters_config')},
        ),
        migrations.RemoveField(
            model_name='mlcube',
            name='image_tarball_hash',
        ),
        migrations.RemoveField(
            model_name='mlcube',
            name='image_tarball_url',
        ),
    ]
