# Generated by Django 4.2.23 on 2025-11-06 12:53

from django.db import migrations, models


def convert_image_hash_from_string_to_json(apps, schema_editor):
    MlCube = apps.get_model("mlcube", "MlCube")
    for mlcube in MlCube.objects.all():
        image_name = mlcube.container_config.get("image", "default")
        mlcube.image_hash_tmp = {image_name: mlcube.image_hash}
        mlcube.save()


def convert_image_hash_from_json_to_str(apps, schema_editor):
    MlCube = apps.get_model("mlcube", "MlCube")
    for mlcube in MlCube.objects.all():
        mlcube.image_hash = list(mlcube.image_hash_tmp.values())[0]
        mlcube.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "mlcube",
            "0005_alter_mlcube_unique_together_alter_mlcube_image_hash_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            code=convert_image_hash_from_string_to_json,
            reverse_code=convert_image_hash_from_json_to_str,
        ),
        migrations.AlterUniqueTogether(
            name="mlcube",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="mlcube",
            name="image_hash_tmp",
            field=models.JSONField(default=dict),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="mlcube",
            unique_together={
                (
                    "image_hash_tmp",
                    "additional_files_tarball_hash",
                    "container_config",
                    "parameters_config",
                )
            },
        ),
        migrations.RemoveField(
            model_name="mlcube",
            name="image_hash",
        ),
        migrations.RenameField(
            model_name="mlcube",
            old_name="image_hash_tmp",
            new_name="image_hash",
        ),
        migrations.AlterUniqueTogether(
            name="mlcube",
            unique_together={
                (
                    "image_hash",
                    "additional_files_tarball_hash",
                    "container_config",
                    "parameters_config",
                )
            },
        ),
    ]
