output_datafile: data.csv
output_imagepath: images
labels:
 - Atelectasis
 - Cardiomegaly
 - Consolidation
 - Edema
 - Enlarged Cardiomediastinum
 - Fracture
 - Lung Lesion
 - Lung Opacity
 - No Finding
 - Pleural Effusion
 - Pleural Other
 - Support Devices
