name: FL Integration workflow

on: pull_request

jobs:
  setup:
    name: fl-integration-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      working-directory: .
      run: |
        python -m pip install --upgrade pip
        pip install -e cli/
        pip install -r cli/test-requirements.txt
        pip install -r server/requirements.txt
        pip install -r server/test-requirements.txt

    - name: Set server environment vars
      working-directory: ./server
      run: cp .env.local.local-auth .env

    - name: Run postgresql server in background
      working-directory: ./server
      run: sh run_dev_postgresql.sh && sleep 6

    - name: Run django server in background with generated certs
      working-directory: ./server
      run: sh setup-dev-server.sh & sleep 6

    - name: Run server integration tests
      working-directory: ./server
      run: python seed.py --cert cert.crt

    - name: Run client integration tests
      working-directory: .
      run: sh cli/cli_tests_training.sh -f